baseURL = "https://kirang89.github.io/kirang.in/"
languageCode = "en-us"
title = "KG – Hacks. Thoughts. Writings."
author = "Kiran Gangadharan"
theme = "black-and-light"

disqusShortname = "kirang89"
pygmentsstyle = "pastie"
pygmentscodefences = true

[params]
  sitename = "KG – Hacks. Thoughts. Writings."
  disableWebFonts = false

# Menu Configuration

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Code"
    url  = "https://github.com/kirang89"
[[menu.main]]
    name = "Resume"
    url = "#"