baseURL = 'http://kirang.in'
languageCode = 'en-us'
title = 'Kiran Gangadharan'
theme = 'paper'
pygmentsstyle = "pastie"
pygmentscodefences = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'catppuccin-frappe'
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[params]
color = 'light'

# header social icons
twitter = 'kirang89'
github = 'kirang89'
linkedin = 'kirang89'

rss = true
# avatar = 'kiran.daredevil@gmail.com'
# name = 'Kiran Gangadharan'
# bio = 'Hacks. Thoughts. Writings.'
monoDarkIcon = true
gravatarCdn = "https://0.gravatar.com/avatar/c5118751c1d02d2650acaa3f6d64ae8b4c68a6f72abbc56e35bd292e0eb2f256?size=128"
favicon = "favicon_32x32.png"
